### ISSUE TITLE
Model Review

### ISSUE THREAD

**Issue by rajeshnath3899** [vipin1006/eHire#1]
Please find my review just on models. 

Change the interviewedBy attribute name in TechnicalFeedBack entity to techLeadName 

Change the interviewedBy attribute name in ManagerFeedback entity to managerName 

Change the interviewedBy attribute name in HrFeedBack entity to hrManagerName 

Relationships name for TechnicalFeedBack , HrFeedBack, ManagerFeedBack can be “candidates” instead of candidate

Candidate entity can have relationship named as interviewedByTechLead , interviewedByManager , interviewedByHr

candidate needs to have  relationship with technology.

Regarding query whether to store the skillSet as binary or transformables , I would suggest why don't we create a another entity called skillSet and map all FeedBack entities(i.e manager, tech leads,hr) as one to many relationships to our skillSet entity.

**Comment by srilatha-sriram** [comment]
Rajesh,  If all the comments are taken care, please close this issue.

**Comment by rajeshnath3899** [comment]
All the above comments are taken care of hence closing this issue
