### ISSUE TITLE
Technial: Default Skill set Shouldn't editable

### ISSUE THREAD

**Issue by padalingam87** [vipin1006/eHire#10]
When you tried to edit a four default skills in skill set it's allow me to do the edit. That should not happen
![screen shot 2016-01-07 at 9 12 58 am](https://cloud.githubusercontent.com/assets/16331589/12161861/d65aba48-b520-11e5-9bb6-50591e4c4394.png)

**Comment by Tharani-p** [comment]
ok.I will work on it.

**Comment by Tharani-p** [comment]
Issue Resolved.

**Comment by padalingam87** [comment]
Issued was solved...  :+1:
