### ISSUE TITLE
SourceList: Contextmenu

### ISSUE THREAD

**Issue by padalingam87** [vipin1006/eHire#12]
In this screen shot java don't have any date but in delete java its showing disclosure ref the diagram
![screen shot 2016-01-07 at 11 37 23 am](https://cloud.githubusercontent.com/assets/16331589/12163438/9f6c0a60-b533-11e5-9f25-d6be2c463cc3.png)

**Comment by Ajayiosdeveloper** [comment]
Ok pada. soon i resolve that and let you know.

**Comment by Ajayiosdeveloper** [comment]
This issue is fixed in every case where context menu is considered.

Many Thanks.

**Comment by padalingam87** [comment]
issue fixed
