### ISSUE TITLE
SourceList: Crashes - multiple while deleting date.

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#14]
Issue 1: Crashed multiple times while deleting dates. Refer screenshots.
![screen shot 2016-01-07 at 12 26 32 pm](https://cloud.githubusercontent.com/assets/16315979/12164283/75a4fb7c-b53a-11e5-90e0-1e0dec48182f.png)
![screen shot 2016-01-07 at 12 26 35 pm](https://cloud.githubusercontent.com/assets/16315979/12164285/75ee6988-b53a-11e5-960b-c6ee996bbded.png)
![screen shot 2016-01-07 at 12 28 47 pm](https://cloud.githubusercontent.com/assets/16315979/12164284/75ee1848-b53a-11e5-9c59-6c1b1f1669c0.png)

Issue 2: Change the warning "Are you sure you want delete" to "Are you sure you want to delete the selected technology". Doesn't the user need to delete all the dates in it first before deleting the technology ? What was decided ?

**Comment by sudhanshu-saraswat** [comment]
ok , i will fix it

**Comment by sudhanshu-saraswat** [comment]
Issue 1 Resolved  : After checking so many times crash not detected.
Issue 2 Resolved  : Changed the warning "Are you sure you want delete" to "Are you sure you want to delete the selected technology"

**Comment by srilatha-sriram** [comment]
Keeping this issue open to see if I can get proper steps for the crashes I saw.

**Comment by srilatha-sriram** [comment]
This issue is not occurring any more. Closing it.
