### ISSUE TITLE
ContextMenu : Its Visible out Side the scope

### ISSUE THREAD

**Issue by padalingam87** [vipin1006/eHire#16]
If right click add technology button the context menu is showing. This should not happen
![screen shot 2016-01-07 at 1 59 29 pm](https://cloud.githubusercontent.com/assets/16331589/12165829/17b4b9a0-b547-11e5-9563-6d8f6e334839.png)

**Comment by rajeshnath3899** [comment]
Ajay can  you fix this issue ASAP

**Comment by Ajayiosdeveloper** [comment]
Sure.i will fix and let you know. 

----- Original Message -----

**Comment by Ajayiosdeveloper** [comment]
Hi Rajesh,

```
          This issue is fixed, tested and checked in.Please have a check and let me know for any changes.
```

**Comment by rajeshnath3899** [comment]
issue fixed and verified hence closing this issue
