### ISSUE TITLE
ContextMenu : Date Pop up is coming when the button is disable

### ISSUE THREAD

**Issue by padalingam87** [vipin1006/eHire#17]
Issue 1: When i add new date through contextmenu the button is disable but its showing a Pop up date.
![screen shot 2016-01-07 at 2 06 51 pm](https://cloud.githubusercontent.com/assets/16331589/12166088/4cfcc588-b549-11e5-8eda-c84ff37b990d.png)

   Issue 2: When you select a technology then the Add Technology button is disable. at the same if you see the context menu Add Technology menu is enable.

![screen shot 2016-01-07 at 2 10 41 pm](https://cloud.githubusercontent.com/assets/16331589/12166107/7769151a-b549-11e5-965f-5fc81542338b.png)

**Comment by Ajayiosdeveloper** [comment]
Issue 1:

Enabling the date Button when adding a date is fixed.

Issue 2:

Here there is a concern.When a technology is selected there is no way out to deselect that.By using ContextMenu option we can easily add a Technology in such cases with out any much trouble and with no conflicts to existing functionalities.

**Comment by padalingam87** [comment]
No need to deselect a outline view. You can disable the Add Technology in Context Menu

**Comment by Ajayiosdeveloper** [comment]
Please read that again discussion and let me know properly.

Many thanks

**Comment by Ajayiosdeveloper** [comment]
Fixed

**Comment by padalingam87** [comment]
Verified  working fine
