### ISSUE TITLE
General: Move commonly used functions to some common utility class

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#18]
Example: isNumberValid function should be available to any class for usage. 

Once you add this in a Common utility class, use that in EHCandidateController to validate phone number & Experience. 
Like this there might be other functions which may be required commonly. If you take care of those, please share the details.

**Comment by padalingam87** [comment]
There will be some number fields in Technology, Candidate and Feedback module. That i will ask the respective people to fix it

**Comment by PratibhaSawargi** [comment]
As of now i have taken the phone number and experience as Strings.So now no need for that numeric validations for these fields.

**Comment by srilatha-sriram** [comment]
Ajay, are you working on this ? Any update ??

**Comment by Ajayiosdeveloper** [comment]
Hi,
i have been working and will complete today.

**Comment by Ajayiosdeveloper** [comment]
Hi Pada,

```
    Commonly used functions are moved to Utilities so far. In EHOnlyDecimalValueFormatter we have a method isNumberValid which is using by many of the Team.As they are using this function for some minor validations that we can not do with another method in EHOnlyDecimalValueFormatter.
```

Use case:  if a textfield that takes a Name of a user but user enters a number in that, then by using this method we can validate whether that is a proper name or simply a number.This can not be done using the another method which does not allow characters to enter.

 Once your Core data part is completed then if any common methods exist then move those to Utilities.

Many Thanks,

Ajay Babu,

Exilant technologies

**Comment by Ajayiosdeveloper** [comment]
Hi Srilatha,

```
         Moving common functions to Utilities is done.Please check that once.
```

**Comment by srilatha-sriram** [comment]
Closing the issue as all the common methods used currently are moved under Utilities group.
