### ISSUE TITLE
SourceList : Added technology is not editable and Add technology Button is disabled

### ISSUE THREAD

**Issue by vipin1006** [vipin1006/eHire#19]
Steps to reproduce:
1. Add new technology on empty source list.
2. delete the technology.
3. Add again technology (it will not be editable)
4. delete the technology ( Add technology button will be disabled)

**Comment by vipin1006** [comment]
Fixed

**Comment by srilatha-sriram** [comment]
Vipin, Why was this assigned to me ? I am not the originator.

**Comment by vipin1006** [comment]
Srilatha Please verify the issue

**Comment by srilatha-sriram** [comment]
Verified. Working fine. Closing.
