### ISSUE TITLE
SourceList: When you add a date, Disclose the triangle.

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#20]
SourceList: When you add a date, Disclose the triangle of the technology under which the date got added. If not, when there is a long list of tech, at that time, this will become confusing.

**Comment by vipin1006** [comment]
I will work on it

**Comment by vipin1006** [comment]
Fixed

**Comment by srilatha-sriram** [comment]
Working fine. Closing.

**Comment by sudhanshu-saraswat** [comment]
Implemented technology sorting in source list please verify.
