### ISSUE TITLE
SourceList: Crashed while adding duplicate tech names

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#21]
SourceList: Crashed while adding duplicate tech names (Refer screenshot 1). It also added the duplicate tech names to core data(Refer screenshot 2). 

![screen shot 2016-01-08 at 12 29 45 pm](https://cloud.githubusercontent.com/assets/16315979/12192345/c340fede-b603-11e5-8f84-445c8dbffdd5.png)
![screen shot 2016-01-08 at 12 32 19 pm](https://cloud.githubusercontent.com/assets/16315979/12192369/e2d6ad8e-b603-11e5-9660-ca8e7391e44e.png)

After giving the error 'Technology name should be unique', it still allowed to add date under empty technology. See screenshot3.
![screen shot 2016-01-08 at 12 37 58 pm](https://cloud.githubusercontent.com/assets/16315979/12192464/c3f352b8-b604-11e5-828f-9a9b2a3e07a4.png)

**Comment by vipin1006** [comment]
Fixed

**Comment by vipin1006** [comment]
Fixed

**Comment by srilatha-sriram** [comment]
Verified. Working fine.
