### ISSUE TITLE
Tech Feedback: Hanging/Uneditable

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#22]
Tech Feedback - Round 1: Clicked submit without entering all the fields. Saw error, "Overall assessment of Candidate field shold not be blank". Clicked OK. and tried to enter data. But the fields became uneditable !
Same thing happened for Round 2.

**Comment by Tharani-p** [comment]
ok.I will work on it.

**Comment by Tharani-p** [comment]
I have fixed this issue and pushed code also. Please have a check and let me know in case any changes is needed.

**Comment by srilatha-sriram** [comment]
Verified. Working fine.
