### ISSUE TITLE
Managerial Feedback - Uneditable after displaying an error.

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#23]
Managerial Feedback - Round 1: Clicked submit without entering all the fields. Saw error, "Overall assessment of Candidate field shold not be blank". Clicked OK. and tried to enter data. But the fields became uneditable !
Same thing happened for Round 2.
When I went back and came again, all the stars became uneditable. But some fields were editable.

**Comment by pavithra123456** [comment]
fixed

**Comment by pavithra123456** [comment]
flow has been changed

**Comment by srilatha-sriram** [comment]
Save is fine. But after 'Submit' the fields are still editable. Need to get the scenario for that..

Meanwhile Technical Rating fields have disappeared.
Refer #26 requirements for proper logic.

**Comment by vipin1006** [comment]
This is fixed.

**Comment by rajeshnath3899** [comment]
issue fixed hence closing it
