### ISSUE TITLE
Managerial: Multiple clicks on save in Round 1 says, Round2, Round 3 saved.

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#25]
Managerial: Multiple clicks on save in Round 1 says, Round2, Round 3 saved.

Enter Managerial Round 1 details. 
Click save 1st time.
Click Save 2nd time without any other change. It says Round 2 details saved.
Click Save 3rd time without any other change. It says Round 3 details saved.
Click Save 4th time without any other change. It says Round 4 details saved.
:
goes on like this !!!

**Comment by pavithra123456** [comment]
Fixed

**Comment by srilatha-sriram** [comment]
The mentioned messages don't come now. Will close this issue.
But Save action is not proper. Follow the requirements mentioned in issue #22.
