### ISSUE TITLE
Technical/Managerial/HR: Have 2 separate buttons Save & Submit

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#26]
NOTE: Once you complete in your module assign to others to completion in other modules.
1. Instead of have a single 'Save' button, have an extra Submit button. This is to avoid the scenario where you click Save, fields will become uneditable and then you realise you need to change something.
   This will also allow a user to enter data incompletely, Save, go back and come again later to continue entering the data.
2. When Save is clicked fields are still editable but the data is Saved. Validations are NOT required for Save.
3. Till 'Submit' is clicked, 'Save' should be kept enabled.
4. When Submit is clicked fields are un-editable and data is saved only after validations.
5. Once 'Submit' is clicked, both 'Save' & 'Submit' and all the fields become disabled.

**Comment by Ajayiosdeveloper** [comment]
Hi Srilatha, 

Please clarify the scenario that relates to submit button.What when user click on Submit with out save button first ? my concern to that point is first check for validation and if its all OK then perform saving and making fields un editable in that case.Is this OK? or do we need 

some way different. 

Regards & Thanks, 

Ajay Babu.s, 

Exilant Technologies. 

----- Original Message -----

**Comment by srilatha-sriram** [comment]
(Note: If you need a comment from me, you should first assign it to me. Otherwise, how will i know ??)

Yes, when submit is clicked directly with out save button first, first check for validation and if its all OK then perform saving and making fields un editable. Here it will be good if you can add a confirmation, 
"Are you sure you want to 'Submit' the data' ?

**Comment by VineetSingh-Exilant** [comment]
Okay..I will work on it.

**Comment by Ajayiosdeveloper** [comment]
Hi Srilatha,

```
            Submit button is implemented in HR module.Relating to Technical and manager Modules, Tharani & Vineet are looking after that.I made them assignees for the rest of the part to be done.
```

**Comment by vipin1006** [comment]
Implemented in managerial module

**Comment by Tharani-p** [comment]
Implemented in Technical Module.

**Comment by srilatha-sriram** [comment]
Verified. Working fine. Closing.
