### ISSUE TITLE
FeedbackView "back" button.

### ISSUE THREAD

**Issue by Tharani-p** [vipin1006/eHire#27]
If the user click on "back" button, we have to show one alert like "Do you want to save the data or not". If user click on "OK", we have to store the data otherwise saving is not needed.

**Comment by Tharani-p** [comment]
I have implemented back button in technical feedback view.You have to implement in manager feedback also.

**Comment by vipin1006** [comment]
It has been implemented in Manager feedback, Ajay you have to implement in HR Feedback

**Comment by Ajayiosdeveloper** [comment]
Hi Srilatha,

```
            Back button for Feedback is integrated for all 3 feedback modules.We need your suggestion for one scenario regarding the UX.Now the flow goes this way,

             When a user clicks on the back button, we are showing one alert for saving the data with OK and cancel.Once User press OK the data is saved and we are also showing another  successful confirmation alert.Is this okay ? or only one alert is sufficient ? We are thinking of why making user stay much time when he/she wants to navigate back.we wait for your reply.
```

Thanks & Regards,

Ajay Babu.s,

Exilant Technologies.

**Comment by srilatha-sriram** [comment]
Ajay, Tharani, Vipin, Vineet,
1. When ‘Save’ is clicked the information should be something like,
   
   Information Saved.
   Feedback for Technical Round has been updated successfully.
   (Only OK button to be shown)
2. When ‘Back’ is clicked the information should be something like,
   
    2.1 (if there is unsaved data/window dirty)
    Do you want to ‘Save’ the data entered before going to the previous screen ?
     (Show ‘Yes’ ‘No’ buttons only)     
   
    2.2 if there is no unsaved data, no need of any confirmation window.
3. When ‘Submit’ is clicked the information should be something like,
   
    3.1 Are you sure you want to ‘Submit’ the data ?
          (Show Yes and No buttons)

**Comment by Tharani-p** [comment]
Fixed the issue as per the requirement.

**Comment by rajeshnath3899** [comment]
Please provide the ETA

**Comment by rajeshnath3899** [comment]
enhancement done
