### ISSUE TITLE
SourceList: Crashing issue in source list

### ISSUE THREAD

**Issue by vipin1006** [vipin1006/eHire#28]
Steps to reproduce:-

1.Click on technology .
2. Click on date inside it.
3. Click on Technology again.
4 Click again on date inside and the application will crash

**Comment by sudhanshu-saraswat** [comment]
i will fix it.

**Comment by sudhanshu-saraswat** [comment]
Issue Resolved please check

**Comment by vipin1006** [comment]
Yeah its working fine now..
