### ISSUE TITLE
Candidate: After emptying the entered phone # field, it allows to go to Feedback

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#29]
1. Enter all details including phone number
2. Deleted phone number
3. Clicked 'Enter Feedback'.
4. Feedback screen opened.

Expected: Should keep the phone number empty and  give that error saying all details have to be entered. Should not go to feedback.

**Comment by PratibhaSawargi** [comment]
Issue resolved.
When phone number field is empty,it is not allowing to go Feedback Module.Please verify and let me know.

**Comment by rajeshnath3899** [comment]
issue fixed and verified hence closing this issue
