### ISSUE TITLE
Issues in Outline View

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#3]
1. FIXED - Once I click on + for adding tech, and then don't give a name, but click somewhere else, that textfield persists. It needs to be removed.
2. Name the + buttons as 'Add Technology'  & 'Add Date' and Keep them on the left. Move the '-' button to right most. This you can do after increasing the minimum width of the Outline View.
3. FIXED - Delete date crashed !
4. FIXED - By default, 'Enter Tech' field came up when app was relaunched !!\

**Comment by sudhanshu-saraswat** [comment]
Name added to  + buttons as  'Add Technology'  &  'Add Date' ,with AutoLayouts.

**Comment by srilatha-sriram** [comment]
Issue 2 - is fixed now and verified.
