### ISSUE TITLE
Managerial/HR: Do not proceed if there is an incomplete Technical Round 2 or 3.

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#30]
Currently if Technical Round 2 or 3 has some dat saved and is incomplete or  not yet submitted, still data is being accepted in Managerial Round and HR Round. The check for incomplete Round 2 and Round 3 data seems to be missing in Managerial & HR.

Ajay/Tharani - once done, assign to the other person,.

**Comment by Tharani-p** [comment]
i have fixed the issue.

**Comment by rajeshnath3899** [comment]
issue fixed hence closing this issue
