### ISSUE TITLE
Managerail/HR/Technical: Add a 'Clear' button to clear all fields.

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#31]
Managerail/HR/Technical: Add a 'Clear' button to clear all fields.

Assign to the next person once done.

**Comment by Tharani-p** [comment]
I have implemented "Clear Button" in Technical and Managerial Feedback.

**Comment by Ajayiosdeveloper** [comment]
okay.I will implement Clear button and also other assigned in HR and let you know. 

Thanks & Regards, 

Ajay Babu.s, 

Exilant Technologies. 

----- Original Message -----

**Comment by padalingam87** [comment]
@Ajayiosdeveloper 
Please don't put company name in Thanks & Regards. Because we are using public repository.

**Comment by Tharani-p** [comment]
Implemented "Clear Button" For HR Module.

**Comment by rajeshnath3899** [comment]
enhancement done
