### ISSUE TITLE
Not going to round2 after submitting in round1in  Technical Module

### ISSUE THREAD

**Issue by VineetSingh-Exilant** [vipin1006/eHire#34]
![screen shot 2016-01-25 at 4 06 27 pm](https://cloud.githubusercontent.com/assets/16332019/12548654/f0ea97aa-c37d-11e5-8b7c-7f17cd71a364.png)
Not going to round2 after submitting in round1.

**Comment by Tharani-p** [comment]
i will work on that.

**Comment by VineetSingh-Exilant** [comment]
Fixed..
