### ISSUE TITLE
Not able to delete the Technology Module

### ISSUE THREAD

**Issue by VineetSingh-Exilant** [vipin1006/eHire#36]
![screen shot 2016-01-25 at 4 14 51 pm](https://cloud.githubusercontent.com/assets/16332019/12548967/ef79473e-c37f-11e5-924a-b13375bb6ee9.png)
Not able to delete blank technology field.

**Comment by sudhanshu-saraswat** [comment]
i will fix it

**Comment by sudhanshu-saraswat** [comment]
Issue Fixed : Not able to delete blank technology field

**Comment by VineetSingh-Exilant** [comment]
Fixed..
