### ISSUE TITLE
Text Field in Technology is not highlighted as soon as Add Technology button is clicked

### ISSUE THREAD

**Issue by rajeshnath3899** [vipin1006/eHire#37]
When add technology button is clicked and once the text field to enter the technology name appears, the user has to click in twice to enter the Technology name 
Steps to reproduce this issue :-  

1) Launch the app 
2) Click on add technology 
3) Double click on technology text field to enter the technology name 

Solution :- Make textFieldTechnology as the First Responder once we click on add technology

**Comment by padalingam87** [comment]
Still we have this issue. We need to create separate example for this scenario and we need find out the solution

**Comment by padalingam87** [comment]
Textfield is highlighted when you add a new technology and issue was fixed

**Comment by rajeshnath3899** [comment]
issue fixed hence closing this issue
