### ISSUE TITLE
Technical Module

### ISSUE THREAD

**Issue by VineetSingh-Exilant** [vipin1006/eHire#39]
Without saving Round 2,we are able to proceed to round 3.

**Comment by Tharani-p** [comment]
Vineet i have fixed that issue. Can you please check it?

**Comment by VineetSingh-Exilant** [comment]
it is crashing..

**Comment by Tharani-p** [comment]
now check it.

**Comment by VineetSingh-Exilant** [comment]
Not working properly.

**Comment by Tharani-p** [comment]
I have fixed the issue in Technical Feedback Module.Vineet you fix the same issue in Managerial Module.

**Comment by VineetSingh-Exilant** [comment]
Okay

**Comment by VineetSingh-Exilant** [comment]
Fixed..Please Verify

**Comment by Tharani-p** [comment]
In Managerial Module its working fine.

**Comment by VineetSingh-Exilant** [comment]
Fixed..
