### ISSUE TITLE
Candidate: Do not allow multiple empty rows

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#4]
Candidate Addition: Do not allow multiple empty rows. Display an error if the user tries to add a new Candidate row if the previously added Candidate information is incomplete.

**Comment by PratibhaSawargi** [comment]
Now it is working fine.

**Comment by PratibhaSawargi** [comment]
Please verify and let me know if any changes required.

**Comment by srilatha-sriram** [comment]
verified. Working fine. Closing the issue.
