### ISSUE TITLE
App crashing..Please refer screen shot.

### ISSUE THREAD

**Issue by VineetSingh-Exilant** [vipin1006/eHire#42]
![screen shot 2016-01-28 at 5 52 40 pm](https://cloud.githubusercontent.com/assets/16332019/12644338/4104d8b0-c5e8-11e5-920b-144ce66b4356.png)

**Comment by sudhanshu-saraswat** [comment]
i will fix it

**Comment by sudhanshu-saraswat** [comment]
Issue Fixed

**Comment by rajeshnath3899** [comment]
issue fixed and verified hence closing this issue
