### ISSUE TITLE
Clear should be disabled once the user starts continuing to enter data after a partial save

### ISSUE THREAD

**Issue by rajeshnath3899** [vipin1006/eHire#44]

**Comment by Tharani-p** [comment]
i will work on it.

**Comment by Tharani-p** [comment]
I have fixed the clear button issue in Technical Feedback Module.

@Vipin/Vineet fix for Manager Feedback Module.

**Comment by VineetSingh-Exilant** [comment]
Fixed..Please Verify

**Comment by Tharani-p** [comment]
fixed the clear button issue in Technical / Managerial Feedback Module.

@Ajay fix for HR Feedback Module.

**Comment by Ajayiosdeveloper** [comment]
sure, i will soon fix and let you know that by noon

**Comment by Ajayiosdeveloper** [comment]
Hi,

This issue has been fixed and tested.Please have a review and let me know if that yet having any issue.

**Comment by rajeshnath3899** [comment]
issue fixed and verified hence closing this issue
