### ISSUE TITLE
Candidate Module# Candidate search bar is not showing proper search results.Refer screen shots.

### ISSUE THREAD

**Issue by sudhanshu-saraswat** [vipin1006/eHire#46]
![screen shot 2016-02-01 at 10 27 43 am](https://cloud.githubusercontent.com/assets/16332003/12709180/0d1fd2ae-c8cf-11e5-9cb6-7f244a21fef0.png)

![screen shot 2016-02-01 at 10 28 02 am](https://cloud.githubusercontent.com/assets/16332003/12709247/d4a481a8-c8cf-11e5-9236-40daf9030f47.png)

**Comment by PratibhaSawargi** [comment]
I will work on it.

**Comment by PratibhaSawargi** [comment]
Fixed the issue #46 : "Candidate search bar is not showing proper search results".
Verify and let me know.

**Comment by sudhanshu-saraswat** [comment]
issue fixed and verified hence closing this issue
