### ISSUE TITLE
Candidate Feedback  form : Date of Interview  is not proper in Personal Details section.Refer Screen shot

### ISSUE THREAD

**Issue by sudhanshu-saraswat** [vipin1006/eHire#47]
![screen shot 2016-02-01 at 11 02 47 am](https://cloud.githubusercontent.com/assets/16332003/12709563/68b5d254-c8d3-11e5-84bf-76ea9a679030.png)

**Comment by Tharani-p** [comment]
fixed..please verify

**Comment by rajeshnath3899** [comment]
issue fixed and verified hence closing this issue
