### ISSUE TITLE
Manager Module we are able to delete the default skills

### ISSUE THREAD

**Issue by rajeshnath3899** [vipin1006/eHire#49]
1) Goto Manager Module 
2) try deleting the defaults skills like growth potential , communication ,organisation stability etc)
3) save the data 

expected scenario 
1) The default skills should not be deleted

**Comment by VineetSingh-Exilant** [comment]
Fixed..Please Verify

**Comment by rajeshnath3899** [comment]
Still I'm able to delete and edit the default skills in managerial module.

**Comment by VineetSingh-Exilant** [comment]
Fixed

**Comment by rajeshnath3899** [comment]
issue fixed and verified hence closing this issue
