### ISSUE TITLE
Candidate: Not allowing to enter name

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#5]
1. Not allowing to enter name after doing a double click.
2. Change 'Give Feedback' label to 'Enter Feedback'.
3. Enable ''Enter Feedback'' button only when a candidate row is selected.

**Comment by PratibhaSawargi** [comment]
Now double click in tableview is working fine.
Changed name to Enter Feedback.
Enter Feedback is enabled only when candidate is selected.

**Comment by srilatha-sriram** [comment]
Verified. Working fine. Closing the issue.
