### ISSUE TITLE
Basic Validations in HR module or few fields are missing

### ISSUE THREAD

**Issue by rajeshnath3899** [vipin1006/eHire#51]
1) Mobile no fields accepts alphanumeric characters
2) have look into email id field as well

**Comment by Ajayiosdeveloper** [comment]
Sure.will let you know once fixed. 

----- Original Message -----

**Comment by Ajayiosdeveloper** [comment]
Hi,
    validations have been verified & fixed.Please verify and let me know.

**Comment by rajeshnath3899** [comment]
still email accept mail id like rajn597@gmail 

it should accept  mail id like rajn597@gmail.com

**Comment by Ajayiosdeveloper** [comment]
Hi, 

Now its been fixed & checked in.Requested to check it once. 

Regards 

----- Original Message -----

**Comment by rajeshnath3899** [comment]
issue fixed and verified hence closing this issue
