### ISSUE TITLE
Clicking on Back button on already saved submitted data

### ISSUE THREAD

**Issue by rajeshnath3899** [vipin1006/eHire#52]
Steps to reproduce 

1) submit a technical round feedback
2) come to main screen and select recently made entry 
3) click on **Enter Feed Back *\* and now click on **Back**
4) we get an alert to save changes

Expected scenario
Alert should not appear if its already completely submitted data

**Comment by rajeshnath3899** [comment]
even if the user did not make any changes its giving me an alert to save the changes and its also storing an empty row to the store file

**Comment by Tharani-p** [comment]
i have implemented for technical module.
@Vineet - fix for manager module.

**Comment by VineetSingh-Exilant** [comment]
I have Implemented in managerial Module.
@Ajay - Fix in HR Module.

**Comment by Ajayiosdeveloper** [comment]
Hi,
This issue is fixed and tested in HR module also.Please review and let me know any issues yet be there.

**Comment by rajeshnath3899** [comment]
repeating the process of saving partially and coming back and then submitting is leading to crash . Im getting an error as follows 

"An uncaught exception was raised
2016-02-08 20:01:29.139 EHire[9869:178543] _registerUndoObject:: NSUndoManager 0x608000086720 is in invalid state, must begin a group before registering undo"

**Comment by rajeshnath3899** [comment]
The above error is happening in technology module please verify the same in other modules

**Comment by rajeshnath3899** [comment]
issue fixed & verified hence closing this issue
