### ISSUE TITLE
SourceList: Allowing to add date to an empty technology

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#6]
Issue 1 - SourceList: Allowing to add date to an empty technology. Refer the screen shot.

Need to validate before adding a date if a tech is entered.

Issue 2: Can add new Tech only when an existing date is selected. How will the user know it ? It should be allowed anytime when a Tech is not selected.

![screen shot 2016-01-06 at 4 25 17 pm](https://cloud.githubusercontent.com/assets/16315979/12141014/234cf68e-b492-11e5-8d48-94f378c7cb84.png)

**Comment by sudhanshu-saraswat** [comment]
ok, i will fix it

**Comment by sudhanshu-saraswat** [comment]
Issue resolved of adding date on empty technology.

**Comment by srilatha-sriram** [comment]
Issue 1 - is working fine. Verified.

Please work on Issue 2. When a tech is selected, if I click else where that tech should be deselected so that I can proceed to add anew tech. Otherwise it will allow me to add only new date and not new tech.

**Comment by sudhanshu-saraswat** [comment]
ok, i will work on it.

**Comment by sudhanshu-saraswat** [comment]
Fixed Issue 2:  When a tech is selected, if I click else where that tech should be deselected so that I can proceed to add anew tech. Otherwise it will allow me to add only new date and not new tech.

**Comment by srilatha-sriram** [comment]
Issue 2: Tech is getting deselected. But both 'Add Tech' and 'Add Date' are enabled. 'Add Date' should be disabled at this point.
New Issue 3: After it got deselected when I pressed add tech, i was not able to enter data in tech name. please check.

**Comment by sudhanshu-saraswat** [comment]
Issue resolved : Tech is getting deselected. But both 'Add Tech' and 'Add Date' are enabled. 'Add Date' should be disabled at this point.

**Comment by srilatha-sriram** [comment]
Verified. Working fine. Closing the issue.
