### ISSUE TITLE
Candidate: Disable button

### ISSUE THREAD

**Issue by padalingam87** [vipin1006/eHire#9]
Delete a candidate and enter the feedback button is enable when there is no candidate in the tableview. It should be disable
![screen shot 2016-01-07 at 9 09 16 am](https://cloud.githubusercontent.com/assets/16331589/12161738/9eb3bbae-b51f-11e5-8ede-de3b5c942cef.png)

**Comment by PratibhaSawargi** [comment]
I will work on it.

**Comment by PratibhaSawargi** [comment]
Issue resolved.

**Comment by padalingam87** [comment]
Can you please check once again?

**Comment by PratibhaSawargi** [comment]
Disable button is working fine.

**Comment by padalingam87** [comment]
Issue was fixed
